
services:

  mmysql:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
    networks:
      em-system-network:
    restart: always
    volumes:
      - ems-data:/var/lib/mysql

  app:
    container_name: employee-backend-container
    build: .
    ports:
      - "8080:8080"
    networks:
      em-system-network:
    restart: always
    depends_on:
      - mmysql

networks:
  em-system-network:
    driver: bridge

volumes:
  ems-data: