export const FETCH_DEPARTMENTS_IN_BATCH_REQUEST = "FETCH_DEPARTMENTS_IN_BATCH_REQUEST";
export const FETCH_DEPARTMENTS_IN_BATCH_SUCCESS = "FETCH_DEPARTMENTS_IN_BATCH_SUCCESS";
export const FETCH_DEPARTMENTS_IN_BATCH_FAILURE = "FETCH_DEPARTMENTS_IN_BATCH_FAILURE";

export const ADD_DEPARTMENT_REQUEST = "ADD_DEPARTMENT_REQUEST";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const UPDATE_DEPARTMENT_REQUEST = "UPDATE_DEPARTMENT_REQUEST";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILURE = "UPDATE_DEPARTMENT_FAILURE";

export const DELETE_DEPARTMENT_REQUEST = "DELETE_DEPARTMENT_REQUEST";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_FAILURE = "DELETE_DEPARTMENT_FAILURE";

export const DEPARTMENT_EMPLOYEES_COUNT = "DEPARTMENT_EMPLOYEES_COUNT";