package com.app.constants;

public enum Event {
    EMPLOYEE_CREATE_SUCCESS,
    EMPLOYEE_CREATE_FAIL,
    EMPLOYEE_DELETE_SUCCESS,
    EMPLOYEE_DELETE_FAIL,
    INCREMENT_SALARY_SUCCESS,
    INCREMENT_SALARY_FAILURE,
    TRANSFER_EMPLOYEE_DEPARTMENT_SUCCESS,
    TRANSFER_EMPLOYEE_DEPARTMENT_FAIL,
    EMPLOYEE_ADD_TO_DEPARTMENT_SUCCESS,
    EMPLOYEE_ADD_TO_DEPARTMENT_FAIL,
    EMPLOYEE_REMOVE_FROM_DEPARTMENT_SUCCESS,
    EMPLOYEE_REMOVE_FROM_DEPARTMENT_FAIL,
    DEPARTMENT_CREATE_SUCCESS,
    DEPARTMENT_CREATE_FAIL,
    DEPARTMENT_DELETE_SUCCESS,
    DEPARTMENT_DELETE_FAIL,
}
