/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Employee;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SalariedEmployees
 */
public class SalariedEmployeesTest {
    private final SalariedEmployees model = new SalariedEmployees();

    /**
     * Model tests for SalariedEmployees
     */
    @Test
    public void testSalariedEmployees() {
        // TODO: test SalariedEmployees
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'salary'
     */
    @Test
    public void salaryTest() {
        // TODO: test salary
    }

    /**
     * Test the property 'employees'
     */
    @Test
    public void employeesTest() {
        // TODO: test employees
    }

}
