/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Department;
import org.openapitools.client.model.DepartmentDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DepartmentControllerApi
 */
@Disabled
public class DepartmentControllerApiTest {

    private final DepartmentControllerApi api = new DepartmentControllerApi();

    /**
     * Add Department
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addDepartmentTest() throws ApiException {
        DepartmentDto departmentDto = null;
        Department response = api.addDepartment(departmentDto);
        // TODO: test validations
    }

    /**
     * List all Departments
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void allDepartmentsTest() throws ApiException {
        List<Department> response = api.allDepartments();
        // TODO: test validations
    }

    /**
     * Delete Department
     *
     * Department must exist
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteDepartmentTest() throws ApiException {
        Integer deptId = null;
        String response = api.deleteDepartment(deptId);
        // TODO: test validations
    }

}
